#!/usr/bin/env python3
"""Build-time helper for the MkDocs site (nothing here is committed).

Creates:
  docs/catalog.md            progress table: published vs. upcoming topics
  docs/<domain>/index.md     landing page per domain
  docs/qa/                   reader Q&A, one page per domain (see qa.py)
  mkdocs.gen.yml             mkdocs.yml + a navigation tree in backlog order
"""
import pathlib
import re

import yaml

from qa import load_entries, render_pages

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"


def slugify(text: str) -> str:
    text = text.lower().replace("&", " and ")
    return re.sub(r"[^a-z0-9]+", "-", text).strip("-")


def front_matter(path: pathlib.Path) -> dict:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    return (yaml.safe_load(m.group(1)) or {}) if m else {}


def main() -> None:
    domains = yaml.safe_load((ROOT / "domains.yaml").read_text())["domains"]
    nav = [{"Home": "index.md"}, {"Catalog": "catalog.md"}]
    rows, total, done = [], 0, 0

    for d in domains:
        folder = DOCS / d["slug"]
        pages = {p.stem: p for p in folder.glob("*.md") if p.name != "index.md"} if folder.exists() else {}
        ordered = []
        for t in d["topics"]:
            total += 1
            slug = slugify(t)
            if slug in pages:
                done += 1
                ordered.append((t, f"{d['slug']}/{slug}.md"))
                rows.append(f"| {d['name']} | [{t}]({d['slug']}/{slug}.md) | ✅ Published |")
            elif d.get("enabled", True):
                rows.append(f"| {d['name']} | {t} | ⏳ Upcoming |")
        # Pages that exist but were removed from the backlog still get listed.
        listed = {slugify(t) for t in d["topics"]}
        for stem, p in sorted(pages.items()):
            if stem not in listed:
                title = front_matter(p).get("title", stem.replace("-", " ").title())
                ordered.append((title, f"{d['slug']}/{stem}.md"))
        if not ordered:
            continue
        links = "\n".join(f"- [{t}]({pathlib.Path(path).name})" for t, path in ordered)
        qa_count = len(load_entries(d["slug"]))
        (folder / "index.md").write_text(
            f"# {d['name']}\n\n{links}\n\n"
            f"**Q&A:** [{qa_count} reader question{'s' if qa_count != 1 else ''} about {d['name']}]"
            f"(../qa/{d['slug']}.md), or add your own.\n",
            encoding="utf-8")
        nav.append({d["name"]: [f"{d['slug']}/index.md"] + [{t: path} for t, path in ordered]})

    cfg = yaml.safe_load((ROOT / "config.yaml").read_text())
    nav.append({"Q&A": render_pages(domains, cfg.get("repo", ""))})
    nav.append({"How We Work": "contributing.md"})
    (DOCS / "catalog.md").write_text(
        "# Catalog\n\n"
        f"**{done} of {total}** topics published.\n\n"
        "| Domain | Topic | Status |\n|---|---|---|\n" + "\n".join(rows) + "\n",
        encoding="utf-8",
    )
    (ROOT / "mkdocs.gen.yml").write_text(
        "# Generated by scripts/build_catalog.py - do not edit\n"
        "INHERIT: mkdocs.yml\n" + yaml.safe_dump({"nav": nav}, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"[catalog] {done}/{total} topics published")


if __name__ == "__main__":
    main()
